# Generated by Django 5.2 on 2025-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=56)),
                ('national_id', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit card'), ('bank_transfer', 'Bank transfer'), ('mortgage', 'Mortgage')], max_length=13)),
                ('card_name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=19)),
                ('card_expiry', models.CharField(blank=True, max_length=5)),
                ('card_cvc', models.CharField(blank=True, max_length=4)),
                ('bank_account', models.CharField(blank=True, max_length=34)),
                ('mortgage_provider', models.CharField(blank=True, max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
