# Generated by Django 5.2 on 2025-05-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finalisation', '0001_initial'),
        ('purchase_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalisation',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalisation', to='purchase_offer.purchaseoffer'),
        ),
    ]
