# Generated by Django 5.2 on 2025-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('agency', 'Real Estate Agency'), ('individual', 'Individual')], max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='sellers/covers/')),
                ('bio', models.TextField(blank=True)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_postal', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
